SELECT C.SCID 
FROM CUSTOMER C
GROUP BY C.SCID
HAVING COUNT(*) >= ALL(SELECT COUNT(*) 
                    FROM CUSTOMER C2
                    GROUP BY C2.SCID);
                    
SELECT AVG(O.PRICE)
FROM OFFERS O
INNER JOIN SERVICE S
ON O.SID = S.SID
WHERE S.SNAME = 'Evaporator Repair' and O.MFG = 'Honda';

SELECT C.FNAME 
FROM CUSTOMER C
WHERE C.SCID = 30003 AND C.ACC_STATUS = 1;

SELECT S.SNAME 
FROM SERVICE S
WHERE S.SID IN (SELECT R.SID 
                FROM REPAIR_SERVICE R
                WHERE R.SID IN (SELECT M.SERVICE_ID
                                FROM MAINTAINANCE_SERVICE M));

                               
SELECT SUM(O.PRICE) as price1
FROM OFFERS O
INNER JOIN SERVICE S
ON O.SID = S.SID 
WHERE O.MFG = 'Toyota' AND O.SCID = 30001 AND (S.SNAME = 'Belt Replacement' OR S.SNAME = 'A');

SELECT SUM(O.PRICE) 
FROM OFFERS O
INNER JOIN SERVICE S
ON O.SID = S.SID 
WHERE O.MFG = 'Toyota' AND O.SCID = 30002 AND (S.SNAME = 'Belt Replacement' OR S.SNAME = 'A');
